### ISSUE TITLE
Verschiedene Profil-Zustände einrichten: Aktiv, inaktiv, gesperrt, gelöscht

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#1]
Mindestens die Profilzustände aktiv und gesperrt sollten eingerichtet werden. :-)

**Comment by srueegger** [comment]
Profilzustände "Gesperrt" und "Gelöscht" können einem User bereits zugewiesen werden (#91). Nun sollten die Funktionen auch noch zum tragen kommen. Sprich der Login der Personen muss verhindert werden, solange diese Profilzustände aktiv sind.

Ebenfalls sollte in der jeweiligen Profilübersicht der Zustand sichtbar sein.

**Comment by aesche** [comment]
Ich wünsche mir noch einen weiteren Profilzustand:
"In Überprüfung"

Muss wohl nicht im Profil angezeigt werden, Nutzungseinschränkungen muss es meiner Meinung nach auch nicht beinhalten, es soll vor allem im Hintergrund die Datenkontrolle vereinfachen:
Wenn ich jemanden finde mit unvollständigen/falschen Angaben, setze ich ihn auf diesen Status.

Dann soll es eine extra Tabelle in der Benutzer-Verwaltung geben, wo nur die Profile mit diesem Status angezeigt werden. So kann ich leicht überprüfen, ob sie der Änderungsaufforderung nachgekommen sind, wenn ja kann ich den Status wieder rausnehmen, wenn nein werden sie nach einer 2. Warnung gesperrt.

**Comment by srueegger** [comment]
Ich schliesse hier wieder. Ich kann den Status nicht der User nicht so einfach ändern.

Viele Funktionen sind darauf ausgelegt, dass der Benutzer den Status 4 (normales Mitglied) hat. Wenn ich diesen Status ändere funktionieren einige Funktionen nicht mehr (z.B. Automatische Weiterleitung bei Datenschutzänderungen, etc) - um das so umzusetzen, muss ich mehrere Änderung an der Codebasis vornehmen, das geht mit #148 einfacher.

Ich hoffe das ist für dich okay so.
