### ISSUE TITLE
Datum-Kalender werden nicht immer angezeigt

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#105]
"Wenn ich nicht im Linux Mint kde und nicht im Open Suse, sondern im Ubuntu 14.04 (immer mit Firefox) auf die Social Meal-Seite gehe, sehe ich die Kalenderli, wo ich sonst nur eine Zeile mit Datum und Zeitangabe sehe."

**Comment by srueegger** [comment]
So. Ich hab mir *kurz* die Mühe gemacht diese Infos zu verwerten. Ich hab in einer Virtuellen Maschine jeweils die aktuellste Version von **Linux Mint KDE** und von ""openSuse** installiert. Ubuntu hab ich ebenfalls getestet (das ist zurzeit auf meinem Rechner installiert). Bei allen 3 Linux Dsitributionen ist Firefox jeweils als Standard-Browser vorinstalliert und vorkonfiguriert.

Bei allen 3 Distributionen hatte ich keine Probleme mit dem Kalender. Grundsätzlich lässt sich folgendes sagen - jeder aktuelle Browser (Firefox ab Version 3, Internet Explorer ab Version 7, Safari ab Version 6 und Chrome <-- seit es ihn gibt) können den Kalender **ohne zusätzliche** Konfiguration darstellen.

Wenn der Kalender **nicht** dargestellt wird, liegt das **nicht** an Social Meal sondern an der Browser Konfiguration. Vielleicht wollte sich jemand super sicher fühlen und hat in den Browser Einstellungen für die Ausführung von JavaScript komplett deaktiviert. Oder er hat irgendein Plugin, dass die Ausführung von (lokalem, bzw direkt eingebunden JavaScript) blockiert. Eine andere Erklärung kann ich hier nicht geben.

Nachfolgend noch die Screenshots aus den Virtuellen Maschinen, bzw von meinem Rechner...

**Linux Mint KDE**
![linux mint kde](https://cloud.githubusercontent.com/assets/11472914/10351823/ef488c3c-6d4b-11e5-8e1e-c8f91b17b2c8.png)

**openSuse**
![opensuse](https://cloud.githubusercontent.com/assets/11472914/10351828/f8aeb26a-6d4b-11e5-9246-56f48890e9bb.png)

**Ubuntu**
![ubuntu](https://cloud.githubusercontent.com/assets/11472914/10351834/ff1c77ae-6d4b-11e5-88fc-a86e8be2b92e.png)
