### ISSUE TITLE
Cookie: Login speichern

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#112]
Ich würde gerne mal in die Runde werfen, das wir doch **ein** Cookie verwenden. Ich finde die Funktion „Login speichern“ wirklich nützlich. Wir können neben der Checkbox gerne auch ein I-Button machen, und ausführlich erklären, das wir damit etwas im Browser der Person speichern.

Da wir die Datenschutzdings ja eh mal ändern wollen - sollten wir das diskutieren.

**Comment by aesche** [comment]
Hab ich mir auch schon überlegt, ist wohl schon ok, sonst sind all deine nummern-icons umsonst...

wie wärs, wenn wir 1 woche vor wettbewerbsende eine pm an alle user schicken, dass wir die Datenschutzrichtlnien ändern (dann kann man da auch noch reinschreiben, dass der Wettbewerb bald ausläuft, gibt hoffentlich noch einen letzten Schub, Newsletter-Öffnung bricht ein...). In der PM wären die alten und provisorisch neuen PMs verlinkt, mit einer Woche Anmerkungsfrist. Die tatsächliche Änderung wär dann 2 Wochen nach dem Wettbewerb.

Opt-In oder Opt-Out? Was muss das Cookie alles speichern? Und wie sieht das mit Sicherheit aus?

**Comment by aesche** [comment]
Hab mich ein bisschen schlauer gemacht über Cookies.
Das wär auf jeden Fall ein eigenes Cookie, das nur das Login bei wiederkehrenden Mitgliedern übernimmt? Also nichts von Dritt-Anbietern und Nutzungsprofil-Erstellung!? Hat das was mit dem eigenen Logging-System zu tun was du haben willst?

**Comment by srueegger** [comment]
Nein hat nichts mit dem Logsystem zu tun. Das Cookie speichert einen 32-stelligen Hashwert. Grundsätzlich würde ich wenn sich jemand einloggt, und die Option "Login speichern" aktiviert, der Person eine fixe Nummer zugewiesen.

Damit ist die Person eindeutig für das System wieder identifizierbar. Die Nummer wäre nicht im Klartext sondern als md5-Hash Wert gespeichert. Weitere Informationen brauche ich dazu nicht.

Ich denke wir wollten auch unbedingt daran festhalten, keine persönlichen Daten (wie E-Mail, Geburtsdatum, etc) in ein Cookie zu speichern, da grundsätzlich jede Webseite alle Cookies auslesen kann.

Von daher kurz zusammengefasst:

* Person will sich einloggen
* Person klickt beim Login auf "Login speichern" (checkbox)
* Bei erfolgreichem Login wird eine eindeutige ID für diesen Benutzer generiert, die nicht die UserID ist.
* Diese ID wird mit einem md5-hash maskiert.
* Die ID wird in der Datenbank gespeichert.
* Die ID wird in einem Cookie gespeichert.
* Wenn die Person (ohne Logout) ein paar Tage später die Webseite wieder aufruft, prüfe ich ob ein Cookie vorhanden ist: -> Wenn Ja, vergleiche ich den Wert in der DB -> wenn die übereinstimmen wird der Login direkt durchgeführt.
* Wenn sich eine Person bewusst über "Logout" ausloggt, wird das Cookie gelöscht.

Das wäre so meine Idee.

**Comment by srueegger** [comment]
Die Funktion funktioniert jetzt. Wenn ein Benutzer die Checkbox "Login speichern" anklickt wird eine 32-stellige ID als Cookie und in der DB abgespeichert. Das Cookie ist 4 Wochen gültig.

Bei einem erneuten Besuch wird der Benutzer automatisch eingeloggt (ausser er hat sich selber über den Logout Button abgemeldet -> da wird das Cookie wieder gelöscht). Die Funktion ist vorerst nur versteckt nutzbar.

**Comment by srueegger** [comment]
Gibt jetzt noch einen InfoButton mit folgendem Text:

Wähle diese Option nicht aus, wenn du dich an einem öffentlichen Computer befindest, da sonst fremde Personen möglicherweise Zugang zu deinem Konto erhalten.
