### ISSUE TITLE
Objektorientiertes arbeiten und diverse Fehlerbehebungen

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#115]
Habe einige Funktionen entdeckt, die noch nicht Objektorientiert umgesetzt sind. (Vor allem im Freunde Bereich)

**Comment by srueegger** [comment]
Im laufe der Zeit haben sich einige Fehler eingeschlichen. Oft weil ich eine Funktion relativ schnell oder unter Zeitdruck oder mit mangelnder Aufmerksamkeit einoperiert habe. Dieses Update hat jetzt ziemlich viel Zeit beansprucht.

Inzwischen sind alle Funktionen komplett Objektorientiert umgesetzt. Und alle Notices und Warnings weg =) - Yaeh.

Das Update ist ziemlich gross, es wurden 40 Dateien bearbeitet.

Insgesamt wurden **915** Zeilen entfernt und **862** Zeilen hinzugefügt - unter dem Strich haben wir damit Code eingesparrt, die Dateigrössen verringert und etwas Ladezeit gewonnen ;-)

**Comment by aesche** [comment]
Cool, vielen Dank :) :+1:
