### ISSUE TITLE
Login: Automatische Weiterleitung ins Admin Dashboard

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#118]
Nach dem Login wird man direkt in den Adminbereich weitergeleitet.

**Comment by aesche** [comment]
noch nicht behoben?

**Comment by srueegger** [comment]
Nein zurzeit gerade Hardcode -> immer auf Profilansicht weitergeleitet.

**Comment by srueegger** [comment]
Gelöst aber nicht referenziert: https://github.com/srueegger/Social-Meal/commit/d58b85541f4b2cfc0e7ca4a40e2fa2cedb4c5a7c

**Comment by aesche** [comment]
Nicht vollständig, oder?

Zwei Probleme:
- Wenn ich bei der Zugriff-Verweigert-Seite das Login vornehme, komme ich immer in mein Profil. Genau da sollte es aber nicht so sein.
- Wenn ich in einem fremden Profil bin, und folglich "Zugriff verweigert" sehe, dann aber nicht dort, sondern via herkömmlichen Login-Button das Login erfolgreich vornehme, werde ich nachher auf eine Seite weitergeleitet, wos heisst "Kein Profil gefunden", Linkbeispiel: https://socialmeal.ch/mein-profil.html?profile=sarah?login=sucess
