### ISSUE TITLE
Checkbox Organisationsprofil: Organisations-Tel-Nr. an Gäste verschicken statt persönliche Tel-Nr.

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#121]
Das Thema haben wir zwar schonmal diskutiert, befriedigend gelöst ist es meiner Meinung nach aber nicht.
Beispiel: Falls Thomas alle Essens-Projekte vom LoLa auf die Plattform stellen soll, will er sicher nicht, dass immer seine persönliche Natelnummer verschickt wird. Dass wir denen die Lösung offen lassen, dass sie die Org-Nr als persönliche Nummer angeben, kanns aber auch nicht sein.

Vorschlag ist analog zur Email-Versendung an die Organisations-Adresse:
Checkbox bei "Organisationsprofil bearbeiten", unterhalb von Organisations-Adresse: "Diese Telefonnummer an teilnehmende Gäste verschicken"
i-Button: Wenn du diese Checkbox auswählst, wird diese Telefonnummer an teilnehmende Gäste verschickt anstatt der persönlichen Telefonnummer des*der Meal-Ersteller*in. Stelle sicher, dass diese Nummer regelmässig, und insbesondere vor bzw zum Beginn von deinem Meals besetzt ist.

(Wollen wir diese Telefonnummer dann verifizieren? Auch wenn wir das bei normalen Profilen nicht tun? Wäre mMn trotzdem überlegenswert, als DL für Organisationen die bei uns werben, was (wenn wir externe Anmeldungen möglichst vermeiden) uns sehr viel bringen kann. Wenn ja, dann Button hinter Nr. mit "Nummer verifizieren", schickt ein E-Mail an uns, Nr. ist direkt verifiziert, und Checkbox kann nur gewählt werden wenn Nr. verifiziert wurde.).

**Comment by srueegger** [comment]
Kann man machen mit Rufnummerverifizierung, leider einfach nicht automatisiert.

**Comment by aesche** [comment]
Oder wir machens wie besprochen ohne Tel-Nr.-Verifizierung, und die Checkbox ist einfach nur sichtbar, wenn überhaupt eine Telefon-Nummer gespeichert ist. Bzw alternativer Vorschlag: Die Checkbox ist immer sichtbar, aber wenn keine Tel-Nr gespeichert ist, wird einfach trotzdem die private Nummer mitgeschickt.

**Comment by srueegger** [comment]
Es macht absolut keinen Sinn eine Checkbox anzuzeigen die keine Funktion hat... ganz ehrlich Nein!

**Comment by aesche** [comment]
Die Lösung ist ok so wie sie jetzt ist. Ganz kleine Anpassung: "... per E-Mail zugeschickt" statt "angezeigt".
