### ISSUE TITLE
Promo-Restaurant-Meals einbauen!

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#123]
Damit wir mit einer ersten Version endlich zum Bacio gehen können und die Fein-Abstimmungen vornehmen können, um danach aktiv nach weiteren Restaurant-Partnern suchen zu können!

Neuer Bereich bei "Neues Meal erstellen":
- Titel: Promo-Meal erstellen
- Dropdown mit allen Promo-Restaurants: Name des Promo-Restaurants (Bio Restaurant Bacio) - Offeriertes Angebot des Restaurants (10% auf alle Bestellungen)
- Button: Neues Promo-Meal erstellen

Fixe Angaben, Beispiel Bacio, angezeigt an Gastgeber im obersten Bereich in Dropdown "Vorgegebene Informationen" auf der Detail-Seite der Meal-Erstellung sowie auf der öffentlichen Meal-Detailseite:
Oberhalb des ersten Anmelde-Buttons (Anzeige auf öffentlicher Meal-Seite):
- Titel: Gemeinsam ins Bio Restaurant Bacio
- Bild: Bild vom Bacio (beim Bacio anfragen für geeignetes Bild) mit Infobalken in einem Bereich mit "10% auf alle Bestellungen"
- Beschreibung des Restaurants: Im Bio Bistro Bacio bekommst du reine Bio-Speisen und -Getränke sowie köstliche ayurvedische Menus! Viraj, der erfahrene ayurvedische Koch, kocht täglich zwei Menus, welche durchgehend genossen werden können. Ayurvedische Menus sind glutenfrei und vegan.
- Promotion für Social Meals: 10% auf alle Bestellungen
- Homepage: http://www.bacio-basel.ch/?p=home
- Speisekarte: Nicht online verfügbar (beim Bacio anfragen für Scan oder so)
Über die Gastgeber (Anzeige auf öffentlicher Meal-Seite):
- Ort: Bio Restaurant Bacio, St. Johanns-Vorstadt 70, CH 4056 Basel
- ÖV: Gut mit dem ÖV erreichbar
- Parkplätze: In 5 Minuten Gehdistanz (beim Bacio nachfragen)
- Karte: Gemäss Adresse
- Rollstuhlgängig: Ja (beim Bacio absichern)

Fixe Angaben, nur dem Gastgeber anzeigen im obersten Bereich in Dropdown "Vorgegebene Informationen" auf der Detail-Seite der Meal-Erstellung:
- Wichtiger Hinweis: Verbindliche Reservation muss spätestens am Vortag direkt beim Bio Restaurant Bacio vorgenommen werden, unter +41 61 322 11 12 oder http://www.bacio-basel.ch/?p=reservation! (Beim Bacio nachfragen ob Abschluss-Email nicht ausreichend ist)

Fixe Angaben, nirgends anzeigen, aber entsprechend in der Datenbank speichern:
- Beschreibung der Zutaten: 3xJa

Variable Angaben, vom Gastgeber auszuwählen gemäss Erstellung von Restaurant-Meals, in Dropdown "Daten zum Meal":
- Meal-Datum*
- Anmeldeschluss*
- Max. Anzahl Gäste*
- Dauer vom Meal
- Beschreibe dein Meal
- Bezahlfunktionen, siehe #16 (nachfragen ob Bacio individuelle Bezahlung akzeptiert)

System-Funktionen:
- E-Mail an Bacio (viraj@bacio-basel.ch) bei Anmeldeschluss mit Name, Adresse und Tel-Nr. des Gastgebers sowie Anzahl definitiver Gäste

**Comment by srueegger** [comment]
Ich werde bei der Entwicklung der Funktion - Schritt für Schritt vorgehen. Die Funktionen sind vorläufig nur für Administratoren sichtbar.

**Comment by srueegger** [comment]
# ACHTUNG!!!

**Ganz wichtig beim testen, keine Meals komplett fertig erstellen**

Nur das Auswahlmenü (Neues Meal erstellen) und das Editierformular (Meal-Bearbeiten) sind für Administratoren sichtbar.

**Wenn das Meal fertig erstellt wird** Ist es öffentlich, deine Freunde werden informiert und der Tweet geht raus, etc...

**Comment by srueegger** [comment]
@aesche Kannst du noch einen E-Mail Mustertext schreiben für das Mail das an den Promo-Partner bei Anmeldeschluss rausgeht?

Sonst ist soweit alles erledigt. Das System ist bewusst modular aufgebaut. Der Aufbau ging dadurch etwas länger, aber so können wir relativ einfach über den Adminbereich neue Promo-Partner hinzufügen, ohne das wir grosse manuelle Anpassungen machen müssen.

**Comment by srueegger** [comment]
Fehlt noch: JavaScript Eingabeüberprüfung für Fallback bei alten Browsern oder Safari.

**Comment by aesche** [comment]
Fehlt noch bei der Admin-Seite: Feld für Telefon-Nummer, Feld für Facebook-Seite
Fehlt noch bei der Erstellen-Seite: Info für den Ersteller wird nicht angezeigt, auch Promotion, Karte als Link, Restaurant-Beschreibung, Tel-Nr, E-Mail und HP könnten angezeigt werden.

Wozu brauchen wir E-Mail an Restaurant überhaupt? Insbesondere, wenn alle etwas anderes wollen... Was wohl sinnvoller und unumgänglich ist: Ein automatisches Dokument für Ersteller, welches er ausgedruckt / mobil dem Personal zeigen kann für den Rabatt (ich mache gleich eine Vorlage).

**Comment by srueegger** [comment]
Die Frage ist ob wir Tel.Nr und FB Seite brauchen. bzw wo zeigen wir den Mist nachher wieder an. Gerade bei FB Seite gibt es ja das Feld Webseite... das reicht meiner Meinung nach vollkommen.

Ich kann deine Lösung gerade nicht anschauen mach ich aber später. Info für den Ersteller wird angezeigt. Halt einfach dann wenn wir diese Infos immer anzeigen, wenn er das Meal gespeichert hat ;-)

**Comment by aesche** [comment]
Ok, dann schreiben wir Tel-Nr halt immer in Info-Box für Ersteller. FB-Seite ist nicht nötig, stimmt, wird ja nur angegeben wenn keine HP vorhanden ist, und dann kanns in das Feld rein.

Info für Ersteller bitte auch schon bei Erstellungs-Seite anzeigen, gerne auch in so einem blauen Balekn.

Auf der "Meal erstellen"-Übersichtsseite muss noch eine zu erstellende Seite verlinkt werden, Titel "Unsere Restaurant-Partner", Verlinkung zwischen Titel und Drop-Down-Menu: "Alle Infos zu den Promotionen unserer Restaurant-Partner"
