### ISSUE TITLE
"Vergangene Meals" in der Profil Ansicht

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#124]
Die Meals werden falsch herum sortiert. ASC statt DESC

**Comment by aesche** [comment]
wüsst ich jetzt nicht ob das falsch ist so. aber was es auf alle fälle sein sollte: einheitlich. bei den vergangenen meals wo man teilgenommen hat ist es atm nämlich garnicht sortiert ;)

**Comment by srueegger** [comment]
Gelöst: Das neuste Meal wird nun immer zuoberst angezeigt.
