### ISSUE TITLE
Widget mit aktuellen Meals für fremde Homepages

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#128]
... Occupy-HP zb...

Das Widget sollte individuell gestaltet werden können:
Wieviele aktuelle Meals anzeigen, welche Kategorien (Fleisch, Vegetarisch, Vegan) eingebunden werden sollen, ...

**Comment by srueegger** [comment]
Einfaches Basiswidget mit den jeweils 3 neusten Meals kann mit dem nachfolgendem HTML-Code eingebunden werden:

<addr><iframe width="275" height="400" src="https://socialmeal.ch/widget.html" frameborder="0"></iframe></addr>

**Comment by srueegger** [comment]
Das Widget ist nun fleixbel anzeigbar.

**Normales Widget ohne Konfiguration**
Das normale Widget ohne Konfiguration zeigt einfach die 3 neusten Meals an.
***Code***
> <iframe width="275" height="400" src="https://socialmeal.ch/widget.html" frameborder="0"></iframe>
