### ISSUE TITLE
Meal ist noch blau, push-Icon aber weg

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#133]
Grosses Rätsel :D

**Comment by aesche** [comment]
auch noch nach logout/login

**Comment by aesche** [comment]
Jetzt waren die push-nummern garnie da, neue meals sind aber blau hinterlegt...

**Comment by srueegger** [comment]
So gross war das Rätsel gar nicht. Das Problem war nur bei dir, dem test account und bei mir.

Da wir die Promo-Meals getestet haben, wurde die bei uns als gesehen markiert. Ich habe die Promo-Meals immer wieder gelöscht - leider wurde dabei der "gelesen" status nicht mitgelöscht, daher hatte das System bei uns immer mehr gesehene Meals als effektiv vorhanden waren.

Von jetzt an, wird der gesehen status beim Meals löschen automatisch mitgelöscht, das ganze sollte wieder reibungslos funktionieren :D
