### ISSUE TITLE
"Meal erstellen"-Seite öffentlich anzeigen

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#135]
Finde es nicht gut, dass einer der Hauptreiter für Gäste schon blockiert ist. Grenze sollte erst einen Schritt später kommen.

Ein Bug ist das ja eigentlich nicht, brauchen wir noch ein Label oder wo ginge das rein?

**Comment by srueegger** [comment]
Man muss ja nicht alles labeln :D 

Hmm könnte man auch machen, das für Gäste dieser Link im Menü gar nicht angezeigt wird? Ich wüsste wirklich nicht, was wir sonst für eine Seite dort hin platzieren wollen...

**Comment by srueegger** [comment]
Das Menü wird nur noch eingeloggten Usern angezeigt. https://github.com/srueegger/Social-Meal/commit/d0ff5572a3fd21e62bd021b02757a78074aa77e6
