### ISSUE TITLE
Schriftbild unter Linux ist eine Katastrophe

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#136]
Das Schriftbild bei den meisten Linux-Installationen wird eine Katastrophe sein. Da die wenigsten die MSCOREFONTS installieren werden.

![bildschirmfoto vom 2015-06-17 08 29 52](https://cloud.githubusercontent.com/assets/11472914/8200879/4830a12e-14cb-11e5-9715-29665185f46c.png)

**Comment by aesche** [comment]
Ich seh das Problem nicht, sieht bei mir genauso aus, FF und Chrome, mal abgesehen davon, dass der ganze Header auf einer Zeile Platz hat.

Feedback zum Thema, siehe E-Mail "kurzes Feedback" vom 17.06.2015:
"– die Erscheinung eurer Homepage finde ich nicht sehr ansprechend, vielleicht würde es sich lohnen, die Seite professionell gestalten zu lassen? Das Auge isst halt wirklich mit ;-)
– ich finde es nicht einfach, mich bei euch zurechtzufinden: vieles ist recht umständlich formuliert (z.B. der Wettbewerb) und ich könnte mir vorstellen, dass manche dafür keine Geduld haben. Ich würde versuchen, das Ganze viel kürzer und klarer zu formulieren, damit man auf den ersten Blick versteht, worum es geht und wie es funktioniert."

**Comment by srueegger** [comment]
>Ich seh das Problem nicht, sieht bei mir genauso aus, FF und Chrome, mal abgesehen davon, dass der ganze Header auf einer Zeile Platz hat.

Das dürfte wohl das Hauptproblem sein. Die Schrift ist da snächste Problem, eigentlich sollte es eine Serifenlose Schrift (Verdana) sein. Ich bin davon ausgegangen, dass die auf jedem Windows Rechner vorinstalliert ist, offenbar ist das aber erst der Fall, wenn jemand auch Microsoft Office installiert hat.

Ich werde Verdana als Hauptschrift lassen, und eine ähnliche Seriefenlose Schrift (die sowohl auf Windows und den meisten Linux Distributionen) vorinstalliert ist, als Alternative definieren, wenn Verdana nicht gefunden wird.

So sollte es eigentlich aussehen:
![seriefenlos](https://cloud.githubusercontent.com/assets/11472914/8234419/2489e534-15dc-11e5-8d7c-41a9fb34259d.png)

**Comment by aesche** [comment]
Ok, sorry, bei mir ist es jeweils die richtige Schrift ohne Serifen. Hab das Problem nicht gesehen.
