### ISSUE TITLE
"Aktivitäten dieses Mitglieds abonnieren"

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#138]
Button in Profil und Meals dieser Person: "Aktivitäten dieses Mitglieds abonnieren".
Dann erhält man ebenfalls ein E-Mail, wenn diese Person ein Meal erstellt, auch wenn man nicht mit ihr befreundet ist.

**Comment by srueegger** [comment]
Macht das bei Mitglieder Sinn? Oder lieber nur bei Organisationen?

**Comment by aesche** [comment]
Ja warum nicht? Will ja nicht mit allen befreundet sein die ich nicht kenne, aber vielleicht merkt jemand, "hei, der bietet immer so feine vegane Menues an, da will ich unbedingt auch mal hin".
Gute Idee, dass das auch bei Organisations-Profilen möglich ist!
