### ISSUE TITLE
Umlautfehler bei Profilen

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#140]
siehe neusten User "väl". Man findet ihn per Suche, der Link ist dann aber falsch, im Adminbereich wird er auch falsch dargestellt.

**Comment by aesche** [comment]
wiederentdeckt: In i-buttons im Profil (Laktoseintoleranz), ev auch in weiteren i-buttons?

**Comment by aesche** [comment]
auch in i-Button bei "Profil bearbeiten", "Nachname"

**Comment by aesche** [comment]
Nein!
In i-buttons im Profil (Laktoseintoleranz und Gluten-Allergie)

**Comment by srueegger** [comment]
Sorry hab nur den unteren Teil mit dem Nachnamen gesehen / gelesen
