### ISSUE TITLE
"Bekannt aus" Medienspiegel im Footer oder auf Extraseite

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#142]
(chronologisch vom Aktuellsten):
- 20min, 19.06.2015: http://www.20min.ch/schweiz/basel/story/24629954
- TeleBasel, 03.04.2015: http://www.telebasel.ch/de/tv-archiv/&id=367728083
- BlickAmAbend, 31.03.2015: http://www.blickamabend.ch/news/mit-fremden-essen-wir-sind-kein-dating-portal-id3618204.html
- OnlineReports, 30.03.2015: http://www.onlinereports.ch/News.117+M5997305478e.0.html
- Zeitpunkt, 30.03.2015 (MM): http://www.zeitpunkt.ch/news/artikel-einzelansicht/artikel/die-menschen-an-einen-tisch-bringen.html
- Untergrund-Blättle, 28.03.2015 (MM): http://www.untergrund-blättle.ch/gesellschaft/social_meal_meal_sharing_fuer_die_region_basel.html
- TagesWoche, 25.03.2015: https://www.tageswoche.ch/de/2015_13/basel/683878/

**Comment by srueegger** [comment]
@aesche Die Seite kannst eigentlich auch du erstellen: Adminbereich -> Datei -> Neu -> Seite :D

**Comment by srueegger** [comment]
Yeah! https://socialmeal.ch/medienspiegel.html
