### ISSUE TITLE
Bewertungs-Seite: "Zum Profil von XY"

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#143]
Auf der Bewertungs-Seite kommt man nirgends zum Profil des Bewertenden, da sollte es einen Button geben. Vorschlag: Ganz oben, oberhalb von "So funktioniert das Bewertungssystem"

**Comment by aesche** [comment]
Wenn man nicht mit der Person befreundet ist und einem der volle Name angezeigt wird, steht da nur "Zum Profil von...". Sollte auch sonst funktionieren, mit Benutzernamen selbstverständlich

**Comment by srueegger** [comment]
https://github.com/srueegger/Social-Meal/commit/c3b2fda1d413a2cd3f810d9e5c825eb0f8c6e334 Erledigt
