### ISSUE TITLE
"Fehler bei Twitter"

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#144]
Hab die Meldung gekriegt als ich mein neues Meal eingestellt hab, ist danach auch nix auf Twitter erschienen!?

**Comment by srueegger** [comment]
Und so das ich verstehe um was es geht? :D

**Comment by srueegger** [comment]
Die Twitter Funktion wurde komplett entfernt und durch #178 ersetzt. Damit ist das Problem behoben.
