### ISSUE TITLE
Datenbanküberprüfung: Vollständige korrekte persönliche Angaben

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#145]
Ich werd das tun und die betreffenden Mitglieder anschreiben, wenn möglich am Montag-morgen. Müsste dann einfach einen aktuellen Datenbank-Auszug haben.

**Comment by srueegger** [comment]
Wo du hier auch immer ein Sicherheitsproblem sehen kannst. Du kannst dir diese Liste selber laden:

* gehe auf http://backup.socialmeal.ch
* Logge dich ein (Daten kommen im FB)
* Klicke links im Mep auf "Backup"
* Wähle die Checkbox "Auswahl bestimmter Tabellen"
* Gebe einen Kommentar ein, damit du dein Backup wiedererkennst: z.B. Userdingsbums oder so :D
* Klicke dann auf neues Backup starten
* Wähle dann die Tabelle: **cl_user** per checkbox
* Klicke unten auf Backup starten
* Danach dauert es einen Moment (auf **keinen* Fall die Seite neuladen)
* Danach sollte so ein Text kommen: "Datei scifitre_sm_2015_06_21_11_06.sql.gz (17.64 KB) wurde erfolgreich erstellt."
* Klicke auf den Dateinamen und du hast deine Daten.
