### ISSUE TITLE
Falscher Link in E-Mail nach Meal

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#147]
In deinem Profil...: https://socialmeal.ch//mein-profil.html

**Comment by srueegger** [comment]
In welchem Mail - also welcher Betreff?

**Comment by aesche** [comment]
Wie war dein Erlebnis beim kürzlich durchgeführten Meal auf Social Meal?

**Comment by srueegger** [comment]
Achso - sorry hab es irgendwie nicht geschnallt.
