### ISSUE TITLE
Benutzerstatus - zur Überprüfung

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#148]
Benutzer müssen mit "Zur Überprüfung" markiert werden können. Die Markierung soll nur im Adminbereich sichtbar sein und wird für interne Zwecke verwendet.

**Comment by aesche** [comment]
Das ist ok so, wenn ich die Tabelle kriegen kann, welche nur die User mit dieser Markierung anzeigt, und ich von dort aus auf die ganzen Profilinfos kommen kann und auch die Markierung wieder entfernen kann. Sonst bringt die Markierung nix, wenn ich sie trotzdem aus der ganzen ID-Liste raussuchen muss.

**Comment by aesche** [comment]
Cool gelöst :)
Kann ich die E-Mail-Adresse von allen wieder angezeit haben in dieser Liste?
