### ISSUE TITLE
Links automatisch erkennen

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#158]
Bei Felder die BBCodes erlauben sollten Links automatisch erkannt werden. Also wenn jemand http://google.ch schreibt sollte das automatisch in <a href="http://google.ch" target="_blank">http://google.ch</a> umgewandelt werden.

**Comment by aesche** [comment]
Funktion ist cool, aber bitte nicht so, dass die per Knopf eingebauten Links rausgerissen und dann erkannt werden...
