### ISSUE TITLE
Teilnahme an Organisationsmeals

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#161]
Organisationsadministratoren sollen sich auch bei Meals von Organisationsprofilen anmelden können.

**Comment by aesche** [comment]
Cool :)

Kann aber noch ausgereifter werden: Beim Meal-Ersteller ist oben rechts ein Chaos (siehe oberes Bild im Screenshot), links sind nur die "Meal bearbeiten"-Buttons (siehe mittleres Bild im Screenshot). Bei Admins die das Meal nicht erstellt haben, sind die Buttons links ganz weg (siehe unteres Bild im Screenshot).

Ausserdem: Wäre gut, wenn alle Admins einen nachträglichen Kommentar anbringen könnten!

Gibt es ein Desaster, wenn ich mich auch anmelde, und mich dann später selber bewerten kann?

https://i.imgur.com/nMQJmhK.png

**Comment by aesche** [comment]
Konkretes Problem bez. Chaos: "Meal bearbeiten" wird dem Ersteller von Organisationsmeals doppelt angezeigt.
