### ISSUE TITLE
Einheitlichkeit Sprache: Gäste oder Teilnehmer*innen

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#167]
Dito Gast oder Teilnehmer*in

Eigentlich dachte ich wir würden insbesondere Gäste nennen und wären nur bei "Meine Meals" umgekippt, wenn ich jetzt aber so rumschau, scheint Teilnehmer*in geläufiger zu sein und wird insbesondere in den AGBs so definiert.

Gast/Gäste wäre aber wohl schöner und insbesondere kürzer und würde zu den Gastgeber*innen passen. Dann würd man halt gleichzeitig zu den Datenschutzrichtlinien auch noch ein paar Begrifflichkeiten in den AGBs ändern, ging ja im Gleichen, dann könnt man auch gleich noch den Rassismus und so explizit nennen...

(Uh, hab gerade auf duden gelesen, dass es das selten gebrauchte Wort Gästin gibt... könnt man aber wohl ignorieren, dh ein nötiges Gendering weniger...)

**Comment by srueegger** [comment]
Alles okay bloss keine Gästinnen :D
