### ISSUE TITLE
komma auf meal-detailseite

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#169]
irgendwo, setzt ein , in die oberste zeile auf der seite

**Comment by aesche** [comment]
Ist das ein Ostereier-Suchspiel?
Auf der Startseite hats auch eins, zwischen Logo und Begrüssungsbalken...

**Comment by aesche** [comment]
und in admin-ansicht und in profilen

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/Social-Meal/commit/e6916ed9eaf19cf59ea9610d37b5e3c518eec107
