### ISSUE TITLE
Login / Zugriff-verweigert-Seite: Hinweis auf Account-Erstellung anpassen

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#176]
Jetzt: Nicht einheitlich (einmal "Neues Profil erstellen", einmal "Bei Social Meal anmelden") und nicht gut genug verständlich.
Vorschlag, bei beiden Seiten gleich: "Du bist noch nicht Mitglied von Social Meal? Erstelle hier ein neues Profil!", ganzen zweiten Satz verlinken mit Anmelde-Seite.

Ausserdem textliche Anpassung im Header "Einloggen" UND bei "Meal erstellen", jeweils 2. Drop-Down-Menu: "Neues Profil erstellen"

**Comment by srueegger** [comment]
Im Menü hab ich die Links angepasst.

Das mit dem nicht einheitlichen vom ersten Teil verstehe ich nicht. Die Links unter dem Formular sind doch einheitlich. Sowohl auf der Login wie auf der Zugriff verweigert Seite.

**Comment by aesche** [comment]
Ich hab die Links unter dem Login-Formular gemeint, welche auf die "Neues Profil erstellen"-Seite verweisen. Das war vorher noch nicht einheitlich, jetzt immerhin schon, könnte aber mit dem längeren vorgeschlagenen Satz ("Du bist noch nicht Mitglied von Social Meal? Erstelle hier ein neues Profil!", ganzen zweiten Satz verlinken mit Anmelde-Seite.) noch deutlicher gemacht werden, da ist ja genügend Platz. Muss aber nicht weiter diskutiert werden, wenn dus nicht länger machen willst, lass es so.
