### ISSUE TITLE
Automatische Social-Media-Postings

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#178]
Homepage -> Facebook -> Twitter anstelle des aktuellen Weges. Weil wir grundsätzlich auf Facebook sind und die Zusatzpostings auch toll auf Twitter wären.

**Comment by srueegger** [comment]
Die neuen Meals werden nun direkt bei Facebook gepostet. Die Twitter posting Funktion wurde komplett entfernt.

Das ganze funktioniert nun nicht über ein JavaScript SDK - sondern über ein PHP SDK. Der Vorteil darin besteht, das wir nichts externes von Facebook einbinden müssen und alles Dateien weiterhin direkt von der Social Meal Domain geladen werden.

Der Nachteil ist, das es enorm viel mehr Code ist.

**Comment by aesche** [comment]
1. Leider übernimmt "Facebook to Twitter" nur persönlich gepostete Statusmitteilungen und nicht automatische Postings... Deshalb muss die Funktion "Social Meal to Twitter" wieder eingebaut werden.

2. Kann der auf Facebook gepostete Text auch ergänzt werden? Vorschlag: "Neues Angebot auf Social Meal: Meal-Titel, am Meal-Datum. Anmeldung:

**Comment by srueegger** [comment]
Punkt 2 ist erledigt. Für Punkt 1 (neues Thema - neue Funktionalität - hat nichts mit Facebook zu tun) ein neues Issue erstellen.

Und bitte ich wiederhole mich hier ständig!!! Erstell doch neue Issues anstatt alte künstlich am Leben zu erhalten. Vorallem dann wenn die neue Funktion (Meals auf Twitter posten) nichts mit der im aktuellen Issue gewünschten Grundfunktionalität (Meals auf Facebook posten) zu tun hat...
