### ISSUE TITLE
Abschlussmail zeitverzögert senden

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#18]
E-Mail "Wie war dein Meal?" 16 Stunden nach Meal-Beginn verschicken

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/www/commit/8f8985ae7ca6da501da02ee4818c889cf1cae88a

**Comment by aesche** [comment]
Oder auch nicht, Rollback zur Vermeidung des angerichteten E-Mail-Schlamassels (Erinnerungsmail habe ich unterdessen 6mal erhalten, wurde auch für ausstehende Events schon verschickt, andere E-Mails wie "ein Meal zu welchem du angemeldet bist findet bald statt" wurden auch zur falschen Zeit verschickt, ...).

**Comment by srueegger** [comment]
Denkanstoss: Neuer Versuch mit dem SQL Intervall Beispiel findet man [hier](http://stackoverflow.com/questions/8544438/mysql-now-1-day)

### Denkanstoss
<addr>WHERE eventdate >= NOW() + INTERVAL 16 HOUR</addr>

**Comment by aesche** [comment]
Wie war dein Erlebnis beim kürzlich durchgeführten Meal auf Social Meal?
Von:	 Social Meal (info@socialmeal.ch)
Gesendet:	Samstag, 27. Juni 2015 23:00:28
An:	fisherman2008@hotmail.com
Kürzlich hat das von dir organisierte Meal Grosses Grillieren + Wettbewerbsverlosung stattgefunden.

**Comment by aesche** [comment]
Die Zeit stimmt jetzt (+16h!?), das E-Mail wird aber doppelt verschickt!

**Comment by srueegger** [comment]
Also ich hab keine doppelten E-Mails mehr erhalten. Und erachte die Sache mal als erledigt bis wieder ein Fehler auftaucht.

Wahrscheinlich wird das so ein "ewiges Problem" oder so xD
