### ISSUE TITLE
Erstellung von neuen Seiten klappt nicht

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#182]
Gilt für Text- und Blogseiten: Zuerst wird nur leere Seite  angezeigt (weil ?blank=true in Link eingebaut wird), wenn man das manuell umgeht kommt zwar Maske zur Seiten-Erstellung, aber wenn man da auf "Erstellen" klickt, kommt wieder die leere Seite mit falschem Link

**Comment by srueegger** [comment]
Klappt wieder
