### ISSUE TITLE
Gross-/Kleinschreibung an diversen Orten

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#192]
Ort - So solls jeweils sein:
Kategorien - Saisonale Produkte
Essen gehen (Seite) - Saisonale Produkte
Essen gehen (Seite) - Regionale Produkte
Essen gehen (Seite) - Meals filtern
Meal finden (Header) - Wähle ein Essen
Zusätzliche Informationen - ist vegetarisch
Zusätzliche Informationen - ist vegan
Beschreibung der Zutaten - Ist das Meal vegetarisch? 
Beschreibung der Zutaten - Ist das Meal vegan?

**Comment by aesche** [comment]
Bei "Vegan" (Kategorie) und "ist vegan" funktionierts ja auch, darum hier ein Reopen, so solls sein:
"enthält saisonale Produkte" und "enthält regionale Produkte" (und bevor du die Kategorien korrigiert hast, war das auch richtig so ;) )

**Comment by srueegger** [comment]
ah mist - das ist schrecklich mit diesen Sprachdateien xD
