### ISSUE TITLE
Gelöschte Profile: Redirect

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#199]
Wenn sich jemand mit einem gelöschten Profil einloggt, reicht es wenn er 1mal die Seite sieht, dass sein Profil gelöscht wurde. bei einem weiteren klick sollte er nichteingeloggt auf die Startseite kommen. oder zumindest sollte logout funktionieren, ist aber irgendwie komisch wenn ja das profil gelöscht ist, wer kommt dann auf die idee sich auszuloggen?

**Comment by srueegger** [comment]
Problem nun komplett gelöst. So wie es eigentlich am meisten Sinn macht. Gelöschte User können sich schlicht nicht mehr einloggen. Es hat den selben Effekt wie ein falsches Passwort oder einen falschen Benutzernamen.
