### ISSUE TITLE
Gelöschte User - Profillink

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#200]
Überall wo ein Profilverlinkt wird, überprüfen ob der User gelöscht ist. Falls ja Den Nutzername in "Gelöschtes Profil" ändern. Die Verlinkung der gelöschten User wie auch die Verifikationsanzeige danach entfernen.

**Comment by aesche** [comment]
Alternativer Vorschlag: Nickname weiterhin anzeigen, aber nicht mehr verlinken. Dahinter Spezial-Icon mit Hover-Text "Dieses Profil wurde gelöscht"
