### ISSUE TITLE
Content Manager: Dateien löschen

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#206]
#150 ist ein grossartiges Update, war schon lange fällig und oft supermühsam. Jetzt hab ich den kleinen Finger und will noch die ganze Hand: Wär cool, wenn man die Dateien auch löschen könnte da, und vielleicht nicht nur den Dateinamen, sondern auch den Titel angezeigt kriegt?

**Comment by aesche** [comment]
Merkwürdig: Beim Dashboard hats die Bearbeiten- und Löschen-Icons nicht, beim Blog schon, aber da kommt bei jedem Link nur "404 Not Found The resource requested could not be found on this server!", hab die Funktionalität der Icons deshalb lieber nicht getestet.

**Comment by srueegger** [comment]
Über das coole rote "X" können Dateien nun gelöscht werden. Aber Achtung es erfolgt keine Sicherheitsfrage, die Datei ist danach umgehend und unwiderruflich gelöscht (kein Papierkorb oder sowas xD)

Über das "Stiftsymbol" kann man Dateien umbenennen. Wenn man eine Datei umbennent die schon auf der Webseite eingebunden ist, muss man diese Seite ebenfalls bearbeiten und dort den neuen Dateinamen eintragen.

Ganz wichtig beim umbennen - unbedingt die Dateiendung nicht vergessen. Also wenn man "BildXY.jpg" umbennent muss der neue Dateiname unbedingt auch wieder mit ".jpg" enden. Da Windows (systembedingt) Dateiendungen braucht, können sonst alle Windows User das Bild/PDF,etc nicht mehr öffnen/anschauen xD
