### ISSUE TITLE
Erfolgsbenachrichtigung bei Profilverifizierung kommt zu spät

### ISSUE THREAD

**Issue by PascalRey** [srueegger/Social-Meal#208]
Hallo Zusammen,
Ich bin mir nicht ganz sicher aber bei der Verifizierung heute auf Socialmeal habe ich den Code eingegeben und zwar praktischerweise eine Erfolgsnachricht in ca. 60 Sekunden per Mail erhalten, aber jedoch keine Bestätigung auf der Plattform selbst das der Code funktioniert hat wenn Ihr versteht was ich meine ;-)
Vielleicht wäre das noch etwas zum anpassen.

LG. Pascal

**Comment by aesche** [comment]
Lieber Pascal

Danke für das Feedback. Eine solche Meldung existiert, hab es gerade schnell durchgeprüft und sie erscheint auch mal, allerdings nicht dann wenn sie sollte.

Genauer Ablauf: Nach der 1. Eingabe des Verifikationscodes kam nochmal die identische Seite, ohne Bestätigung, aber mit dem Feld um den Code einzugeben. Das Bestätigungs-Email habe ich schon gekriegt. Ich hab den Code dann nochmal eingegeben, und dann ist die Erfolgsmeldung gekommen.

Funktioniert hat die Verifizierung bei dir auf alle Fälle, du hast den grünen Haken hinter deinem Namen.

Lg Stefan

**Comment by srueegger** [comment]
Danke fürs Melden. Problem ist gelöst :D
