### ISSUE TITLE
Punkte Rang-/Mitgliederliste

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#210]
@aesche 

Da das Punktesystem (#32) gute Fortschritte macht. Sollten wir uns überlegen ob es auch eine öffentliche (nur für angemeldete) Rangliste geben soll - das würde den Wettbewerb etwas fördern.
Da das Konzept einer Mitgliederliste sehr ähnlich ist, und ich irgendwie im Kopf hatten, das wir sowas nicht wollen, sollten wir das hier erneut diskutieren.

Brauchen wir das oder eher nicht?

**Comment by aesche** [comment]
Ich würde sagen Nein. Dass die Punkte im Profil von allen sichtbar ist ok, oder da vielleicht sogar auch nur der Rang. Sehe in einer Liste keinen wirklichen Mehrgewinn.

Hab mir aber auch schon ein Anreizsystem überlegt, dass die Punkte eben nicht nur Rangpunkte sind, sondern gleichzeitig auch Credits, mit denen man hin und wieder was ersteigern kann.

**Comment by srueegger** [comment]
closed - da wir ja keine Punkte/Rangliste machen.
