### ISSUE TITLE
Schutz vor "Brute Force" Attacken.

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#212]
Wenn mehrmals ein flasches Passwort hintereinander von der selben IP Adresse eingegeben wird, sollte die IP Adresse (mindestens) temporär für Social Meal gesperrt werden.

--> Einfachste Lösung über die .htaccess Datei.

**Comment by srueegger** [comment]
@aesche Was hälst du von dieser Idee:
 Der Loginprozess wurde bereits künstlich um 3 Sekunden verlängert. Das merkt der normale User nicht direkt. Aber man kann nun nicht mehr innerhalb von einer Sekunde automatisiert mehrere Passwörter auswählen.

Nun folgender Vorschlag: Es gibt einen Fail-Login Counter: Wenn sich jemand 10 mal mit falschem Passwort versucht einzuloggen, geht automatisch ein Mail an die Person. Inhalt: "Wir haben festgestellt das sie sich nicht einloggen können, kennen sie schon passwort vergessen funktion bla"

Ab dem 10. mal wird der Loginversuch künstlich um 10 (statt) 3 Sekunden verlängert. Beim 25. Loginversuch wird das Profil gesperrt. Es geht wieder eine an den User (und an uns) raus - um ihn darüber in Kenntnis zu setzen. Und er sich direkt an uns wenden soll.

Wenn zwischen dem 1. und 25 Login ein Loginversuch gelingt wird der "Fail-Login Counter" wieder auf 0 gesetzt.

Man könnte auch einbauen das beim 1. Loginversuch keine künstliche Verzögerung gibt.

**Comment by aesche** [comment]
Ich finde all diese Ideen ganz gut!

Ich frage mich aber, ob die erfolglosen Versuche nicht zu hoch gesetzt sind. Wären 5 Missversuche bis zur Warnung (welche unbedingt auch auf der Seite in einem neuen Balken angezeigt werden sollte) und 10 bis zur Sperrung nicht auch ausreichend? Dann würde sich die künstliche Verzögerung wohl auch erübrigen.

**Comment by srueegger** [comment]
kann man auch so machen.

**Comment by aesche** [comment]
- Nach 3 Fehlversuchen zusätzlicher Hinweis im Fehler-Balken "Der Login ist fehlgeschlagen!": Hier[Link] kannst du ein neues Passwort beantragen.
- Nach 20 Fehlversuchen: Automatische Sperrung des Profils + E-Mail an Besitzer + E-Mail an info@socialmeal.ch

**Comment by srueegger** [comment]
Ein etwas grösserer Commit. Aber es funktioniet. Nach 3 Fehlversuchen wird der "FAILED" - Banner mit dem Hinweis auf Passwort vergessen erweitert.

Nach 20 Versuchen wird das Profil gesperrt. Und ein E-Mail an den User und an Social Meal gesendet.

**Comment by srueegger** [comment]
Zusatz: Der "False-Login Counter" findet man auch im Adminbereich wenn man einen User bearbeitet. Als Admin kann man dort den Counter ändern - gut zum testen der Funktion wenn man den selbst vorher auf 19 setzt ;-)

**Comment by srueegger** [comment]
Gesperrte User werden jetzt im Adminbereich markiert. Beim Autologin wird der false-login Counter wieder auf 0 gesetzt.
