### ISSUE TITLE
Teilweiser Datenbank-Verlust!

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#219]
Ist vielfrass (ID 342) aufgefallen, weil sie immer auf Profilbearbeitung gezwungen wurde, und sonst nix tun konnte. Überprüfung ergab, dass Ihr Name + Vorname nicht mehr gespeichert war. Beim Registrierungs-Email war er aber noch da. Hab ich unterdessen behoben, damit sie ihr Profil nutzen kann.

Weitere fehlende Daten:
ID 344: alles
ID 338: alles
ID 337: alles
ID 335: Vor- und Nachname
ID 334: Vor- und Nachname

Und teilweise fehlt "Letzte Bewegung", zb ID 328, 323, 322, 309, 288, 274, 264, 238, 234, 233
-> Bei all denen wird auch als letztes Login die Zeit der Admin-Profil-Seitenaufrufung angezeigt!!???

Alles durchgecheckt bis runter auf ID 233.

Neben Issue #220 kann auch deine kürzliche Account-Löschung nicht für das Problem gesorgt haben, ID 334 und 335 hatten das Problem schon davor.

**Comment by aesche** [comment]
Noch nicht behoben: 
Und teilweise fehlt "Letzte Bewegung", zb ID 328, 323, 322, 309, 288, 274, 264, 238, 234, 233
-> Bei all denen wird auch als letztes Login die Zeit der Admin-Profil-Seitenaufrufung angezeigt!!???

**Comment by aesche** [comment]
Scheint gelöst zu sein, bei den letzten drei Anmeldungen hats geklappt. Musst du bei der Schliessung ev noch mit einem Commit ergänzen?

**Comment by srueegger** [comment]
Nein muss ich nicht - schliesse es.
