### ISSUE TITLE
Anzeige nie eingeloggte User

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#221]
Bisher: Benutzer, vor 2016 Jahren online
Besser: Benutzer, noch nie online
Z.B. mit einer Testfunktion, wenn letztes Login > 5 Jahre -> nie online

**Comment by srueegger** [comment]
Ist ugesetzt. Allerdings ohne Abfrage ob jemand 5 Jahre nicht online war. Weil wir sonst in 5 Jahren falsche Ergebnisse haben. Es wird effektiv überprüft ob sich bisher jemand eingeloggt hat oder nicht.
