### ISSUE TITLE
Meal-Name nicht im Seitentitel

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#222]
Irgendetwas Unerklärliches (Sonderzeichen sinds wohl nicht, funktionieren bei anderen aktuellen Meals bzw den vergangenen Filmabenden) führt dazu, dass beim aktuellen Filmabend-Event (ID 213) der Meal-Name nicht im Seitentitel erscheint. Wenn ich auf "bearbeiten" klicke dann aber schon!???

**Comment by srueegger** [comment]
Das Problem, war ein Copy&Paste Problem vom Filmtitel. Offenbar haben wir einen Gedankenstrich statt einem Bindestrich eingefügt. Da der Gedankenstrich als merkwürdiges Sonderzeichen interpretiert wurde kam das System ins Stocken.

Problem ist gelöst-
