### ISSUE TITLE
Umlautfehler Meal-Anmeldung

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#223]
Du hast dich bereits fÃ¼r dieses Meal angemeldet!

Zusatzfrage: Erscheint der "Teilnehmen"-Button bei allen Meals wenn man schon angemeldet ist oder nur für Admins von Spezialmeals? Das macht ja eigentlich wenig Sinn.

**Comment by srueegger** [comment]
Der Teilnehmen Button erscheint nur bei Admins von Spezial Meals. Wir haben dazu auch ein Issue: #161
