### ISSUE TITLE
Mehrere Mails

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#227]
Offenbar werden einige Mails mehrfach verschickt. Das "Anmeldefrist abgelaufen" Mail sollte zukünftig über eine extra "cronjob" Datei ereledigt werden umd solche Probleme zu verhinden.

**Comment by srueegger** [comment]
Die Mails sollten jetzt nicht mehr doppelt kommen. Bisher haben wir ja über einen Cronjob alle 5 Minuten die Social Meal Webseite aufgerufen, um den Mailversand auszulösen. Ich kann mir vorstellen das es da zu Doppel- oder Mehrfach Mails gekommen ist wenn der Cronjob gleichzeitig mit einem richtigen User eine Seite aufgerufen hat.

Alle Mails:
(Bewertungserinnerung, Anmeldefrist, Adresse)
werden nun über eine spezielle Datein (cron.php) versendet. Diese Datei wird von einem User nie geöffnet sondern nur vom Cronjob selbst.

Zu Dokumentationszwecke der Crontab Befehl:
*/5 * * * * curl https://socialmeal.ch/cron.php > /dev/null 2>&1

**Comment by aesche** [comment]
Hoffen wir das Beste, auch wenn ich deine Vermutung nicht wirklich verstehe, bzw dadurch für unwahrscheinlich halte, weil die Mails alle innerhalb einer Minute gekommen sind. Für deine Vermutung spricht, dass du genau in der Minute zwei Klicks gemacht hast auf der Seite.
