### ISSUE TITLE
E-Mail-Fehler bei Meal-Erstellung

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#229]
Mail Error:You must provide at least one recipient email address.

**Comment by aesche** [comment]
Wahrscheinlich auch damit verknüpft, bei der Anmeldung zum Meal:
Mail Error:SMTP connect() failed.Mail Error:SMTP connect() failed.
Anmeldung hat geklappt, hab dann aber auch keine E-Mails an occupy/mich erhalten.

**Comment by srueegger** [comment]
Wahrscheinlich damit verknüpft, das du alle Mail Passwörter ohne vorherige Absprache geändert hast. Das Social Meal E-Mail System funktioniert wie Thunderbird oder ein andere E-Mail Client - er logt sich per SMTP bei info@socialmeal.ch ein um E-Mails zu versenden. Dazu braucht er das Passwort ;-)
