### ISSUE TITLE
Meals X Anzahl Plätze frei

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#23]
Startseite Meal-Kurzvorschau: Anzeige von „Freie Plätze: X von Y“ (alternativ bei Spezial-Meals „Unbeschränkt“) unterhalb des Datums

**Comment by srueegger** [comment]
Macht durchaus auch auf der "Meal finden" und in der Meal Detailansicht Sinn.

**Comment by srueegger** [comment]
Auf der Startseite, Meal finden und Meal Detailansicht wird das nun angezeigt: https://github.com/srueegger/www/commit/8df9b6cc5f1e7bdc659ca93b7ca0e62e7e28c73a

**Comment by aesche** [comment]
Es wäre die schönere Lösung, wenn bei unbeschränkten (nach Umsetzung von #75 solls auch andere geben) Spezial-Meals "Max. Anzahl Gäste: Unbeschränkt" (und das auch so angezeigt wird in der Meal-Detailansicht) und "Freie Plätze: Ja" stehen würde und das dementsprechend auch so überall angezeigt würde.
Würde den Reiz erhöhen sich trotzdem da anzumelden, Ja tönt eher so als ob es mal auf Nein kippen könnte als "Unbeschränkt"! (Siehe neues Issue #168)

**Comment by srueegger** [comment]
Wenn ich das richtig verstehe keine "X von Y" Plätze frei sondern nur noch Ja oder Nein. Ich hätte da einen besseren Gegenvorschlag.

Wenn mehr als ein Platz verfügbar ist nur "Ja" anzeigen (vorallem auf der Startseite und Meal-finden Seite). Wenn aber nur noch 1 Platz frei ist, wieder die aktuelle Anzeige "1 von Y" Plätze frei. Ich denke das führt dazu das der letzte Platz schneller besetzt wird, weil es impliziert, das der Gast sich schnell anmelden muss wenn er noch rein will...

Was hälst du davon?

**Comment by aesche** [comment]
Du hast ein entscheidendes Detail überlesen, und zwar dass sich mein Vorschlag auf die unbeschränkten Spezial-Meals beschränkt. Weil "unbeschränkt" impliziert, dass es ewig Platz hat, also kein Grund sich anzumelden. "Ja" kann aber auch mal "Nein" werden wenn man nicht weiss, dass der Organisator "unbeschränkt" angekreuzt hat.

Von der Ausdehnung davon oder deinem Mittelweg halte ich dementsprechend nicht viel ;)
