### ISSUE TITLE
Wochentag, Datum

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#236]
Überall (Startseite Mealvorschau, Infobalken und Blogvorschau, Meal- und Blog-Datum, Frage- und Antwort, Bewertungen, PMs, Widget ...) wo das Datum mit Wochentag angezeigt wird, fehlt das Komma zwischen dem Wochentag und dem Datum.

(Wäre es jetzt nicht passender gewesen, wenn ich für so einen kleinen Mist #160 wiedereröffnet hätte, als ein neues Issue zu machen?)

**Comment by srueegger** [comment]
Nein passt schon so. So kann man die Commits jeweils einem festen Problem zuordnen. Wenn aber diverse Probleme unter einer Nummer gelöst werden - und ich nachher alle commits der Nummer anschaue muss ich doch wieder im Code suchen mit welcher Änderung ich nun welches Problem gelöst habe.

**Comment by aesche** [comment]
Leider trotdzem nochmal: Bei Blog-Kommentaren fehlt der Wochentag ganz

**Comment by srueegger** [comment]
Bei den Kommentaren wird das Datum nun auch richtig angezeigt.

Kategorie und Beiträge von einem Autor funktionieren bei mir einwandfrei.
