### ISSUE TITLE
Falsches Meal-Bild wird auf Facebook geteilt

### ISSUE THREAD

**Issue by srueegger** [srueegger/Social-Meal#6]
* Passiert insbesondere dann, wenn zu kleine Bilder hochgeladen werden
* Passiert seltener aber auch bei grossen Bildern: Bei neuem Spaghetti-Meal wurde falsches Bild geteilt, bei altem Spaghetti-Meal das richtige…

**Comment by aesche** [comment]
Vielleicht könnte das Problem eher lokalisiert werden, wenn die Posts direkt von SocialMeal kommen und nicht über Twitter umgeleitet werden!? Wenn ich #117 richtig verstanden habe, würd das auch dafür sprechen.

**Comment by srueegger** [comment]
Du hast #117 falsch verstanden. Es spielt keine Rolle woher Facebook den Link erhält. Er holt die Informationen aus dem Link, ob der über Twitter, manuell von dir oder über Social Meal kommt spielt dabei keine Rolle.

Bei 117 ging es darum das in der FB Textvorschau (Die er auch direkt vom Link holt) logischerweise die [bbcodes] drin waren, weil ich bei der bbcode implementierung vergessen hab, das zeug in den Meta Daten umzuwandeln...

**Comment by srueegger** [comment]
Meiner Meinung nach gibt es nur eine Möglichkeit das sinnvoll zu lösen. In dem wir die Meals nicht direkt veröffentlichen sondern vorher Redaktionell bearbeiten.

**Comment by srueegger** [comment]
Dank #178 sollte das Problem ereldigt sein. Mit dem Facebook SDK lade ich das gewünschte Bild nun direkt bei Facebook hoch.

Wenn ein Gastgeber kein Bild ausgewählt hat wird stattdessen unser Logo hochgeladen. Habe beides mehrmals getestet und funktionierte einwandfrei!

Das einzige Problem was es noch geben kann, ist wenn das Meal-Bild zu klein. Dieses Problem löst sich aber mit #134. Falls (und ich gehe nicht davon aus) es wieder zu random Bilder kommt kann das Issue erneut geöffnet werden.
