### ISSUE TITLE
Gross- und Kleinschreibung in Benutzernamen beibehalten

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#67]
Eingegebene Benutzernamen nicht kleinmachen. Eingabe bei Login nicht case-sensitiv

**Comment by srueegger** [comment]
man sollte dabei beachten, dass der Login aber nur funktioniert, wenn der entsprechende User beim Login sein Username dann auch in der richtigen Gross/Kleinschreibung eingibt..

**Comment by aesche** [comment]
nein warum? "Eingabe bei Login nicht case-sensitiv"
