### ISSUE TITLE
Offene + versteckte Adresse bei Spezial-Meals

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#70]

**Comment by srueegger** [comment]
Funktioniert einwandfrei...

![bildschirmfoto 2015-05-17 um 13 54 53](https://cloud.githubusercontent.com/assets/11472914/7670237/6a2f3548-fc9c-11e4-9df7-8181c04ea2c1.png)
![bildschirmfoto 2015-05-17 um 13 55 30](https://cloud.githubusercontent.com/assets/11472914/7670238/6a58061c-fc9c-11e4-802a-9f5be5382282.png)

**Comment by aesche** [comment]
Guten Morgen Sam

**Comment by aesche** [comment]
Denkfehler gefunden: Wenn Adresse nicht öffentlich angezeigt werden soll, sollte der Veranstaltungsort auch nicht angezeigt werden!

Zusatzfrage: Wird Veranstaltungsort in E-Mail an Gast "Meal findet bald statt" mitgeschickt?
