### ISSUE TITLE
Verschiedene Benutzernamen können wegen Sonderzeichen nicht angezeigt werden seit Datenbankverlust

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#74]
Unbedingt beheben:
Benutzername:
- ID 51, 82

Auch wichtig: Umlaute in Vorname, Nachname, Strassenname flicken

**Comment by srueegger** [comment]
Benutzername bei den IDs 51 und 82 ist behoben

**Comment by aesche** [comment]
Ja? Sämi heisst jetzt Samy und thüring kann nicht in der Suche gefunden werden?

**Comment by aesche** [comment]
vorgeschlagene Lösung für Adressen und "Über mich": Benutzer-Datenbank-Tabelle exportieren, Sonderzeichen suchen und ersetzen, Tabelle wieder importieren

**Comment by srueegger** [comment]
Erledigt
