### ISSUE TITLE
E-Mail-Adresse in "Profil bearbeiten" anzeigen...

### ISSUE THREAD

**Issue by aesche** [srueegger/Social-Meal#78]
...  zumindest als fixes Feld wie Benutzername mit Option auf manuelle Anpassung auf Anfrage.
... oder editierbares Feld falls jemand seine E-Mail wechseln will, nach Änderung muss ein neuer E-Mail-Bestätigungs-Vorgang abgeschlossen werden.

**Comment by srueegger** [comment]
Erst muss https://github.com/srueegger/www/issues/1 abgearbeitet werden, damit ein Account automatisch gesperrt wird, bis die neue E-Mail Adresse bestätigt wird.

**Comment by srueegger** [comment]
E-Mail wird jetzt einfach angezeigt - ohne weitere Funktion: https://github.com/srueegger/www/commit/3a9c2369053b3e6e708c4016ef92ff5d82264bed

**Comment by aesche** [comment]
- E-Mail-Feld: Jederzeit bearbeitbar. Aber wenn neue E-Mail gespeichert wird, wird Profil gesperrt (NICHT komplett sperren, Profilbearbeitung muss offen bleiben falls falsche E-Mail eingegeben wurde) und E-Mail für E-Mail-Verifizierung verschickt.
- Wenn du deine E-Mail-Adresse änderst, wird dir ein E-Mail geschickt mit einem Link um die neue E-Mail-Adresse zu bestätigen. Bis dann ist es dir nicht möglich die Funktionen von Social Meal zu nutzen. Wenn du das Mail nicht findest, schaue in deinem Spam-Ordner nach. Wenn auch das nicht hilft $Link[kontaktiere uns].

E-Mail-Vorlage für E-Mail-Verifizierung:
Titel: Verifiziere deine neue E-Mail-Adresse auf Social Meal
Text:
"Liebe * r $Vorname

Soeben hast du auf Social Meal die Verifizierung dieser E-Mail-Adresse für dein Profil  $Link[$Bentuzername] beantragt.

Klicke auf diesen Link um die E-Mail-Adresse zu verifizieren: $Link
Danach stehen dir die Funktionen von Social Meal wieder im vollen Umfang zur Verfügung.

Vielen dank für dein Engagement.
Social Meal

Signatur"
